#!/bin/sh
set -e

# --- Script Variables

PACKAGE_NAME="debian-config-aide"

TARGET_USER="_aide"
TARGET_GROUP="_aide"

LIB_DIR="/var/lib/aide"
LOG_DIR="/var/log/aide"

UPDATE_HOOK_SCRIPT="/usr/libexec/debian-config-aide/aide-update-hook.sh"

# --- Helper Functions ---

set_lib_directory_permissions() {
    if [ -d "${LIB_DIR}" ]; then
        echo "${PACKAGE_NAME}: Setting AIDE library directory permissions at ${LIB_DIR}"
        chown "${TARGET_USER}":"${TARGET_GROUP}" "${LIB_DIR}"
    else
        echo "${PACKAGE_NAME}: Creating AIDE library directory at ${LIB_DIR}"
        mkdir -p "${LIB_DIR}"
        chown "${TARGET_USER}":"${TARGET_GROUP}" "${LIB_DIR}"
    fi
}

set_log_directory_permissions() {
    if [ -d "${LOG_DIR}" ]; then
        echo "${PACKAGE_NAME}: Setting AIDE log directory permissions on ${LOG_DIR}"
        chown "${TARGET_USER}":adm "${LOG_DIR}"
    else
        echo "${PACKAGE_NAME}: Creating AIDE log directory at ${LOG_DIR}"
        mkdir -p "${LOG_DIR}"
        chown "${TARGET_USER}":adm "${LOG_DIR}"
    fi
}

set_hookscript_permissions() {
    if [ -f "${UPDATE_HOOK_SCRIPT}" ]; then
        echo "${PACKAGE_NAME}: Setting AIDE hookscript permissions on ${UPDATE_HOOK_SCRIPT}"
        chown "${TARGET_USER}":"${TARGET_GROUP}" "${UPDATE_HOOK_SCRIPT}"
    fi
}

run_aide_init() {
    echo "${PACKAGE_NAME}: Initializing AIDE database. This could take awhile..."
    aideinit -y -f
}

fix_aide_database_permissions() {
    echo "${PACKAGE_NAME}: Fixing permissions on AIDE database file"
    chown "${TARGET_USER}":"${TARGET_GROUP}" "${LIB_DIR}/aide.db"
}

# --- Main Logic Execution ---

case "$1" in
    configure)
        set_hookscript_permissions
        set_log_directory_permissions
        set_lib_directory_permissions

        run_aide_init
        fix_aide_database_permissions
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        if [ "${1}" = '' ]; then
            ARG="none"
        else
            ARG="${1}"
        fi
        echo "${PACKAGE_NAME}: postinst called with unknown argument \`${ARG}\`" >&2
        exit 1
        ;;
esac

# Automatically injects standard debhelper maintenance routines
#DEBHELPER#

exit 0
