# /etc/fail2ban/jail.d/99-sshd-hardening.conf
# Managed by debian-config-sshd package

[sshd]
enabled  = true
port     = ssh
mode     = aggressive
backend  = systemd
maxretry = 3
findtime = 10m
bantime  = 1h

# Incremental ban times for repeat offenders
bantime.increment = true
bantime.factor    = 2
bantime.maxtime   = 4w
