#!/bin/sh
set -e

PACKAGE_NAME="debian-config-clamav"
SCRIPT_NAME="postinst"

# --- Helper Functions ---

enable_clamav_scan_daily_timer() {
    if [ -x "/usr/bin/deb-systemd-helper" ]; then
        echo "${PACKAGE_NAME}: Enabling clamav-scan-daily timer..."
        deb-systemd-helper enable clamav-scan-daily.timer >/dev/null || true
    fi
}

start_clamav_scan_daily_timer() {
    if [ -x "/usr/bin/deb-systemd-invoke" ]; then
        echo "${PACKAGE_NAME}: Starting clamav-scan-daily timer..."
        deb-systemd-invoke start clamav-scan-daily.timer >/dev/null || true
    fi
}

# --- Main Logic Execution ---

case "$1" in
    install|upgrade)
		# Start once daily update service
        enable_clamav_scan_daily_timer
		start_clamav_scan_daily_timer
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    *)
        if [ "${1}" = '' ]; then
            ARG="none"
        else
            ARG="${1}"
        fi
        echo "${PACKAGE_NAME}: ${SCRIPT_NAME} called with unknown argument \`${ARG}\`" >&2
        exit 1
        ;;
esac

# Automatically injects standard debhelper maintenance routines
#DEBHELPER#

exit 0
