#!/bin/sh
set -e

PACKAGE_NAME="debian-config-lowmem"
SCRIPT_NAME="prerm"

# --- Helper Functions ---



# --- Main Logic Execution ---

case "$1" in
    remove|upgrade)
        ;;

	failed-upgrade)
	    ;;

    *)
        if [ "${1}" = '' ]; then
            ARG="none"
        else
            ARG="${1}"
        fi
        echo "${PACKAGE_NAME}: ${SCRIPT_NAME} called with unknown argument \`${ARG}\`" >&2
        exit 1
        ;;
        
esac

# Automatically injects standard debhelper maintenance routines
#DEBHELPER#

exit 0
