# /etc/ssh/sshd_config.d/50-system-hardening.conf
# Managed by debian-config-system-hardening package

# Restrict Authentication
AllowGroups ssh-users sudo
PasswordAuthentication no
PermitEmptyPasswords no
PermitRootLogin prohibit-password
MaxAuthTries 3

# Session Management
ClientAliveCountMax 2
ClientAliveInterval 600
MaxSessions 2

# Network & Protocol
AllowAgentForwarding no
AllowTcpForwarding no
DisableForwarding yes
TCPKeepAlive no
X11Forwarding no

# Log Details for Security Audits
LogLevel VERBOSE
