#!/bin/sh
set -e

PACKAGE_NAME="debian-config-sshd"
SCRIPT_NAME="preinst"

# --- Helper Functions ---



# --- Main Logic Execution ---

case "$1" in
    install|upgrade|abort-upgrade)
    ;;
        
    *)
        ARG="${1:-none}"
        echo "${PACKAGE_NAME}: ${SCRIPT_NAME} called with unknown argument \`${ARG}\`" >&2
        exit 1
    ;;

esac

# Automatically injects standard debhelper maintenance routines
#DEBHELPER#

exit 0
